// <auto-generated />
using System;
using BotGardens.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BotGardens.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240725110130_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BotGardens.Domain.Entities.BiometricData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("InventoryNumber");

                    b.ToTable("BiometricDatas");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Family", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.PhenologicalData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservationYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Phenophase")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("InventoryNumber");

                    b.ToTable("PhenologicalDatas");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ConservationStatus")
                        .HasColumnType("text");

                    b.Property<string>("DeterminedBy")
                        .HasColumnType("text");

                    b.Property<string>("DuplicatesInOtherHerbaria")
                        .HasColumnType("text");

                    b.Property<string>("EcologyAndBiology")
                        .HasColumnType("text");

                    b.Property<string>("EconomicUse")
                        .HasColumnType("text");

                    b.Property<int>("FamilyID")
                        .HasColumnType("integer");

                    b.Property<string>("FilledBy")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .HasColumnType("text");

                    b.Property<bool>("HasHerbarium")
                        .HasColumnType("boolean");

                    b.Property<string>("Illustration")
                        .HasColumnType("text");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("NaturalHabitat")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Originator")
                        .HasColumnType("text");

                    b.Property<string>("PlantingYear")
                        .HasColumnType("text");

                    b.Property<string>("SampleOrigin")
                        .HasColumnType("text");

                    b.Property<int>("SectorID")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .HasColumnType("text");

                    b.Property<string>("Variety")
                        .HasColumnType("text");

                    b.Property<string>("YearCountry")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("LocationID");

                    b.HasIndex("SectorID");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.BiometricData", b =>
                {
                    b.HasOne("BotGardens.Domain.Entities.Plant", "Plant")
                        .WithMany("BiometricDatas")
                        .HasForeignKey("InventoryNumber")
                        .HasPrincipalKey("InventoryNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.PhenologicalData", b =>
                {
                    b.HasOne("BotGardens.Domain.Entities.Plant", "Plant")
                        .WithMany("PhenologicalDatas")
                        .HasForeignKey("InventoryNumber")
                        .HasPrincipalKey("InventoryNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Plant", b =>
                {
                    b.HasOne("BotGardens.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotGardens.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BotGardens.Domain.Entities.Sector", "Sector")
                        .WithMany("Plants")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Location");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Plant", b =>
                {
                    b.Navigation("BiometricDatas");

                    b.Navigation("PhenologicalDatas");
                });

            modelBuilder.Entity("BotGardens.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
