// <auto-generated />
using System;
using BotGarden.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BotGarden.Infrastructure.Migrations
{
    [DbContext(typeof(BotanicGardenContext))]
    [Migration("20250302104137_AddLocationIdToExposition")]
    partial class AddLocationIdToExposition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("BotGarden.Domain.Models.Biometry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<float?>("FlowerDiameter")
                        .HasColumnType("real");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float?>("MeasurementValue")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Biometries", (string)null);
                });

            modelBuilder.Entity("BotGarden.Domain.Models.BotGardenModel", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("LocationId"));

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<string>("LocationPath")
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("BotGarden");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Exposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Expositions", (string)null);
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("GenusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Genus");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Map", b =>
                {
                    b.Property<int>("MapImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("MapImageId"));

                    b.Property<string>("MapImagePath")
                        .HasColumnType("text")
                        .HasColumnName("MapImagePath");

                    b.HasKey("MapImageId");

                    b.ToTable("Map");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Phenology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FloweringEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FloweringStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FruitingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeafAppearanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Phenologies", (string)null);
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Areal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("BotGardenModelLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("DeterminedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EcologyBiology")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EconomicUse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ExpositionId")
                        .HasColumnType("integer");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("FilledBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("GenusId")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasDuplicates")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHerbarium")
                        .HasColumnType("boolean");

                    b.Property<string>("Illustration")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Originator")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Rod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SectorsId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Vid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("YearCountry")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("YearOfPlanting")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotGardenModelLocationId");

                    b.HasIndex("ExpositionId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("GenusId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("SectorsId");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Sectors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("BotGardens.Domain.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserHashedPass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Biometry", b =>
                {
                    b.HasOne("BotGarden.Domain.Models.Plant", "Plant")
                        .WithMany("Biometries")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Exposition", b =>
                {
                    b.HasOne("BotGarden.Domain.Models.BotGardenModel", "Location")
                        .WithOne("Exposition")
                        .HasForeignKey("BotGarden.Domain.Models.Exposition", "LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Phenology", b =>
                {
                    b.HasOne("BotGarden.Domain.Models.Plant", "Plant")
                        .WithMany("Phenologies")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Plant", b =>
                {
                    b.HasOne("BotGarden.Domain.Models.BotGardenModel", null)
                        .WithMany("Plants")
                        .HasForeignKey("BotGardenModelLocationId");

                    b.HasOne("BotGarden.Domain.Models.Exposition", "Exposition")
                        .WithMany("Plants")
                        .HasForeignKey("ExpositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BotGarden.Domain.Models.Family", "Family")
                        .WithMany("Plants")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BotGarden.Domain.Models.Genus", null)
                        .WithMany("Plants")
                        .HasForeignKey("GenusId");

                    b.HasOne("BotGarden.Domain.Models.Sectors", null)
                        .WithMany("Plants")
                        .HasForeignKey("SectorsId");

                    b.Navigation("Exposition");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.BotGardenModel", b =>
                {
                    b.Navigation("Exposition");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Exposition", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Family", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Genus", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Plant", b =>
                {
                    b.Navigation("Biometries");

                    b.Navigation("Phenologies");
                });

            modelBuilder.Entity("BotGarden.Domain.Models.Sectors", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
